"""adicionar itens no Pedido

Revision ID: 257fdeaa478b
Revises: 5a3457a6f1e2
Create Date: 2026-02-17 11:06:02.717544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257fdeaa478b'
down_revision: Union[str, Sequence[str], None] = '5a3457a6f1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
